#!/bin/bash

#installs a package in different linux distributions

installpack()
{
if [[ "$(apt)" == *"Usage:"* ]]; 
then
  	echo "using apt"
	sudo apt install $1 -y
else
	echo "using pacman"
	sudo pacman -Sy $1
fi
}
