#!/bin/sh


#Author - Peter Wolf
#21-10-2024
#dougalite@gmail.com

#Simple network configuration for the purpose of hardening a live linux system

sudo chmod a+x ./currentinterface.pl

sudo ip link set multicast off dev $(perl ./currentinterface.pl)
#sudo ip link set broadcast off dev $myinterface

