#!/bin/bash

#ufw setup
#Author - Peter Wolf
#dougalite@gmail.com
#20-10-2024

#This is specific to my situation and needs to be edited if someone else is going to use it.


sudo ufw enable
sudo ufw logging low
sudo ufw deny 67
sudo ufw deny 68
sudo ufw deny to 192.168.0.255

while read ip; do
        sudo ufw deny from $ip
        sudo ufw deny to $ip
        echo "Blocked $ip"    
done < ipstoblock
